"""initial schema

Revision ID: b8f5af17e79d
Revises:
Create Date: 2026-08-14 16:48:56.315526+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic_utils.pg_policy import PGPolicy
from sqlalchemy.dialects import postgresql

from alembic import op
from app.domain.apps.enums import AppState
from app.domain.users.roles import Role
from app.platform.comms.enums import MessageDirection, MessageState
from app.platform.dashboard.enums import WidgetType
from app.platform.documents.enums import DocumentStates
from app.platform.events.enums import EventType
from app.platform.form_dsl.enums import FormNodeKind
from app.platform.llm.enums import MessageRole
from app.platform.media.enums import MediaStates
from app.platform.queue.enums import TaskStatus
from app.platform.utils.sqids import SqidType
from app.platform.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "b8f5af17e79d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("state", TextEnum(DocumentStates), server_default="PENDING", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_key"),
    )
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_documents_state"), "documents", ["state"], unique=False)
    op.create_table(
        "event_consumer_failures",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("consumer_key", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_consumer_failures_consumer_key"), "event_consumer_failures", ["consumer_key"], unique=False
    )
    op.create_index(
        op.f("ix_event_consumer_failures_deleted_at"), "event_consumer_failures", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_event_consumer_failures_event_id"), "event_consumer_failures", ["event_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("event_type", TextEnum(EventType), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_actor_id"), "events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_events_deleted_at"), "events", ["deleted_at"], unique=False)
    op.create_index("ix_events_object", "events", ["object_type", "object_id", "created_at"], unique=False)
    op.create_index("ix_events_org_created", "events", ["organization_id", "created_at"], unique=False)
    op.create_index(op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False)
    op.create_table(
        "llm_threads",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("threadable_type", sa.Text(), nullable=True),
        sa.Column("threadable_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_threads_deleted_at"), "llm_threads", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_llm_threads_threadable_id"), "llm_threads", ["threadable_id"], unique=False)
    op.create_index(op.f("ix_llm_threads_threadable_type"), "llm_threads", ["threadable_type"], unique=False)
    op.create_index(op.f("ix_llm_threads_user_id"), "llm_threads", ["user_id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False)
    op.create_table(
        "state_transition_logs",
        sa.Column("object_type", sa.String(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("from_state", sa.String(), nullable=False),
        sa.Column("to_state", sa.String(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_state_transition_logs_deleted_at"), "state_transition_logs", ["deleted_at"], unique=False)
    op.create_index("ix_stl_object_lookup", "state_transition_logs", ["object_type", "object_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("job_key", sa.Text(), nullable=False),
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("status", TextEnum(TaskStatus), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_deleted_at"), "tasks", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tasks_job_key"), "tasks", ["job_key"], unique=True)
    op.create_index(op.f("ix_tasks_task_name"), "tasks", ["task_name"], unique=False)
    op.create_table(
        "threads",
        sa.Column("threadable_type", sa.Text(), nullable=False),
        sa.Column("threadable_id", sa.Integer(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("threadable_type", "threadable_id", name="uq_thread_per_object"),
    )
    op.create_index(op.f("ix_threads_deleted_at"), "threads", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_threads_threadable_id"), "threads", ["threadable_id"], unique=False)
    op.create_index(op.f("ix_threads_threadable_type"), "threads", ["threadable_type"], unique=False)
    op.create_table(
        "apps",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("repo_url", sa.Text(), nullable=False),
        sa.Column("state", TextEnum(AppState), server_default="registered", nullable=False),
        sa.Column("search_trgm", sa.Text(), sa.Computed("coalesce(name, '')", persisted=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apps_deleted_at"), "apps", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_apps_state"), "apps", ["state"], unique=False)
    op.create_table(
        "business_sequences",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("current_value", sa.BigInteger(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "type", name="uq_business_sequences_org_type"),
    )
    op.create_index(op.f("ix_business_sequences_deleted_at"), "business_sequences", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_business_sequences_organization_id"), "business_sequences", ["organization_id"], unique=False
    )
    op.create_table(
        "form_nodes",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("owner_type", sa.Text(), nullable=False),
        sa.Column("owner_id", SqidType(), nullable=False),
        sa.Column("parent_id", SqidType(), nullable=True),
        sa.Column("kind", TextEnum(FormNodeKind), nullable=False),
        sa.Column("schema_ref", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_id"], ["form_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_form_nodes_deleted_at"), "form_nodes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_form_nodes_organization_id"), "form_nodes", ["organization_id"], unique=False)
    op.create_index("ix_form_nodes_owner", "form_nodes", ["owner_type", "owner_id"], unique=False)
    op.create_index(op.f("ix_form_nodes_parent_id"), "form_nodes", ["parent_id"], unique=False)
    op.create_table(
        "llm_messages",
        sa.Column("thread_id", SqidType(), nullable=False),
        sa.Column("role", TextEnum(MessageRole), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["thread_id"], ["llm_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_messages_deleted_at"), "llm_messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_llm_messages_thread_id"), "llm_messages", ["thread_id"], unique=False)
    op.create_table(
        "media",
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("state", TextEnum(MediaStates), server_default="PENDING", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_key"),
    )
    op.create_index(op.f("ix_media_deleted_at"), "media", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_media_organization_id"), "media", ["organization_id"], unique=False)
    op.create_index(op.f("ix_media_state"), "media", ["state"], unique=False)
    op.create_table(
        "messages",
        sa.Column("thread_id", SqidType(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_deleted_at"), "messages", ["deleted_at"], unique=False)
    op.create_index("ix_messages_thread_created", "messages", ["thread_id", "created_at"], unique=False)
    op.create_index(op.f("ix_messages_thread_id"), "messages", ["thread_id"], unique=False)
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    op.create_table(
        "thread_read_statuses",
        sa.Column("thread_id", SqidType(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_thread_read_status_lookup", "thread_read_statuses", ["thread_id", "user_id", "read_at"], unique=False
    )
    op.create_index(op.f("ix_thread_read_statuses_deleted_at"), "thread_read_statuses", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_thread_read_statuses_thread_id"), "thread_read_statuses", ["thread_id"], unique=False)
    op.create_index(op.f("ix_thread_read_statuses_user_id"), "thread_read_statuses", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("role", TextEnum(Role), server_default="CLIENT", nullable=False),
        sa.Column("organization_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "dashboards",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dashboards_deleted_at"), "dashboards", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_dashboards_user_id"), "dashboards", ["user_id"], unique=True)
    op.create_table(
        "email_threads",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_threads_archived_at"), "email_threads", ["archived_at"], unique=False)
    op.create_index(op.f("ix_email_threads_deleted_at"), "email_threads", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_email_threads_user_id"), "email_threads", ["user_id"], unique=False)
    op.create_table(
        "llm_tool_calls",
        sa.Column("message_id", SqidType(), nullable=False),
        sa.Column("tool_use_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "input", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("is_error", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["llm_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_tool_calls_deleted_at"), "llm_tool_calls", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_llm_tool_calls_message_id"), "llm_tool_calls", ["message_id"], unique=False)
    op.create_table(
        "magic_link_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_magic_link_tokens_deleted_at"), "magic_link_tokens", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_magic_link_tokens_token_hash"), "magic_link_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_magic_link_tokens_user_id"), "magic_link_tokens", ["user_id"], unique=False)
    op.create_table(
        "email_messages",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("email_thread_id", SqidType(), nullable=True),
        sa.Column("direction", TextEnum(MessageDirection), nullable=False),
        sa.Column("state", TextEnum(MessageState), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("from_email", sa.Text(), nullable=True),
        sa.Column("from_name", sa.Text(), nullable=True),
        sa.Column("to_emails", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("rfc_message_id", sa.Text(), nullable=True),
        sa.Column("in_reply_to", sa.Text(), nullable=True),
        sa.Column("attachments_json", sa.JSON(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("s3_bucket", sa.Text(), nullable=True),
        sa.Column("s3_key", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("spf_pass", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("dkim_pass", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_automated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reply_to_email", sa.Text(), nullable=True),
        sa.Column("template_name", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("(direction = 'OUT') OR (s3_key IS NOT NULL)", name="ck_inbound_has_s3_key"),
        sa.ForeignKeyConstraint(["email_thread_id"], ["email_threads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(op.f("ix_email_messages_archived_at"), "email_messages", ["archived_at"], unique=False)
    op.create_index(op.f("ix_email_messages_deleted_at"), "email_messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_email_messages_email_thread_id"), "email_messages", ["email_thread_id"], unique=False)
    op.create_index(op.f("ix_email_messages_rfc_message_id"), "email_messages", ["rfc_message_id"], unique=True)
    op.create_index(op.f("ix_email_messages_ses_message_id"), "email_messages", ["ses_message_id"], unique=True)
    op.create_index("ix_email_messages_user_archived", "email_messages", ["user_id", "archived_at"], unique=False)
    op.create_index(op.f("ix_email_messages_user_id"), "email_messages", ["user_id"], unique=False)
    op.create_index("ix_email_messages_user_thread", "email_messages", ["user_id", "email_thread_id"], unique=False)
    op.create_table(
        "widgets",
        sa.Column("dashboard_id", SqidType(), nullable=False),
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("type", TextEnum(WidgetType), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "query", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("position_x", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("position_y", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("size_w", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("size_h", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_widgets_dashboard_id"), "widgets", ["dashboard_id"], unique=False)
    op.create_index(op.f("ix_widgets_deleted_at"), "widgets", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_widgets_user_id"), "widgets", ["user_id"], unique=False)
    op.enable_rls("public", "organizations")
    public_organizations_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.organizations",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_organizations_org_scope_policy)

    op.enable_rls("public", "apps")
    public_apps_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.apps",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND apps.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_apps_org_scope_policy)

    op.enable_rls("public", "business_sequences")
    public_business_sequences_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.business_sequences",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND business_sequences.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_business_sequences_org_scope_policy)

    op.enable_rls("public", "form_nodes")
    public_form_nodes_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.form_nodes",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND form_nodes.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_form_nodes_org_scope_policy)

    op.enable_rls("public", "media")
    public_media_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.media",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND media.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.create_entity(public_media_org_scope_policy)

    op.enable_rls("public", "dashboards")
    public_dashboards_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.dashboards",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.create_entity(public_dashboards_user_scope_policy)

    op.enable_rls("public", "email_threads")
    public_email_threads_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.email_threads",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.create_entity(public_email_threads_user_scope_policy)

    op.enable_rls("public", "email_messages")
    public_email_messages_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.email_messages",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.create_entity(public_email_messages_user_scope_policy)

    op.enable_rls("public", "widgets")
    public_widgets_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.widgets",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.create_entity(public_widgets_user_scope_policy)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_widgets_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.widgets",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_widgets_user_scope_policy)

    op.disable_rls("public", "widgets")
    public_email_messages_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.email_messages",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_email_messages_user_scope_policy)

    op.disable_rls("public", "email_messages")
    public_email_threads_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.email_threads",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_email_threads_user_scope_policy)

    op.disable_rls("public", "email_threads")
    public_dashboards_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.dashboards",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.user_id', true), '') IS NOT NULL\n            AND user_id = NULLIF(current_setting('app.user_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_dashboards_user_scope_policy)

    op.disable_rls("public", "dashboards")
    public_media_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.media",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND media.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_media_org_scope_policy)

    op.disable_rls("public", "media")
    public_form_nodes_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.form_nodes",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND form_nodes.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_form_nodes_org_scope_policy)

    op.disable_rls("public", "form_nodes")
    public_business_sequences_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.business_sequences",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND business_sequences.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_business_sequences_org_scope_policy)

    op.disable_rls("public", "business_sequences")
    public_apps_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.apps",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND apps.organization_id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_apps_org_scope_policy)

    op.disable_rls("public", "apps")
    public_organizations_org_scope_policy = PGPolicy(
        schema="public",
        signature="org_scope_policy",
        on_entity="public.organizations",
        definition="AS PERMISSIVE\n    FOR ALL\n    USING (\n        NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n        OR (NULLIF(current_setting('app.organization_id', true), '') IS NOT NULL\n            AND id = NULLIF(current_setting('app.organization_id', true), '')::int)\n    )",
    )
    op.drop_entity(public_organizations_org_scope_policy)

    op.disable_rls("public", "organizations")
    op.drop_index(op.f("ix_widgets_user_id"), table_name="widgets")
    op.drop_index(op.f("ix_widgets_deleted_at"), table_name="widgets")
    op.drop_index(op.f("ix_widgets_dashboard_id"), table_name="widgets")
    op.drop_table("widgets")
    op.drop_index("ix_email_messages_user_thread", table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_user_id"), table_name="email_messages")
    op.drop_index("ix_email_messages_user_archived", table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_ses_message_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_rfc_message_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_email_thread_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_deleted_at"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_archived_at"), table_name="email_messages")
    op.drop_table("email_messages")
    op.drop_index(op.f("ix_magic_link_tokens_user_id"), table_name="magic_link_tokens")
    op.drop_index(op.f("ix_magic_link_tokens_token_hash"), table_name="magic_link_tokens")
    op.drop_index(op.f("ix_magic_link_tokens_deleted_at"), table_name="magic_link_tokens")
    op.drop_table("magic_link_tokens")
    op.drop_index(op.f("ix_llm_tool_calls_message_id"), table_name="llm_tool_calls")
    op.drop_index(op.f("ix_llm_tool_calls_deleted_at"), table_name="llm_tool_calls")
    op.drop_table("llm_tool_calls")
    op.drop_index(op.f("ix_email_threads_user_id"), table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_deleted_at"), table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_archived_at"), table_name="email_threads")
    op.drop_table("email_threads")
    op.drop_index(op.f("ix_dashboards_user_id"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_deleted_at"), table_name="dashboards")
    op.drop_table("dashboards")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_thread_read_statuses_user_id"), table_name="thread_read_statuses")
    op.drop_index(op.f("ix_thread_read_statuses_thread_id"), table_name="thread_read_statuses")
    op.drop_index(op.f("ix_thread_read_statuses_deleted_at"), table_name="thread_read_statuses")
    op.drop_index("ix_thread_read_status_lookup", table_name="thread_read_statuses")
    op.drop_table("thread_read_statuses")
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_thread_id"), table_name="messages")
    op.drop_index("ix_messages_thread_created", table_name="messages")
    op.drop_index(op.f("ix_messages_deleted_at"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_media_state"), table_name="media")
    op.drop_index(op.f("ix_media_organization_id"), table_name="media")
    op.drop_index(op.f("ix_media_deleted_at"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_llm_messages_thread_id"), table_name="llm_messages")
    op.drop_index(op.f("ix_llm_messages_deleted_at"), table_name="llm_messages")
    op.drop_table("llm_messages")
    op.drop_index(op.f("ix_form_nodes_parent_id"), table_name="form_nodes")
    op.drop_index("ix_form_nodes_owner", table_name="form_nodes")
    op.drop_index(op.f("ix_form_nodes_organization_id"), table_name="form_nodes")
    op.drop_index(op.f("ix_form_nodes_deleted_at"), table_name="form_nodes")
    op.drop_table("form_nodes")
    op.drop_index(op.f("ix_business_sequences_organization_id"), table_name="business_sequences")
    op.drop_index(op.f("ix_business_sequences_deleted_at"), table_name="business_sequences")
    op.drop_table("business_sequences")
    op.drop_index(op.f("ix_apps_state"), table_name="apps")
    op.drop_index(op.f("ix_apps_deleted_at"), table_name="apps")
    op.drop_table("apps")
    op.drop_index(op.f("ix_threads_threadable_type"), table_name="threads")
    op.drop_index(op.f("ix_threads_threadable_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_deleted_at"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_tasks_task_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_key"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_deleted_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_stl_object_lookup", table_name="state_transition_logs")
    op.drop_index(op.f("ix_state_transition_logs_deleted_at"), table_name="state_transition_logs")
    op.drop_table("state_transition_logs")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_llm_threads_user_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_threadable_type"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_threadable_id"), table_name="llm_threads")
    op.drop_index(op.f("ix_llm_threads_deleted_at"), table_name="llm_threads")
    op.drop_table("llm_threads")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_index("ix_events_org_created", table_name="events")
    op.drop_index("ix_events_object", table_name="events")
    op.drop_index(op.f("ix_events_deleted_at"), table_name="events")
    op.drop_index(op.f("ix_events_actor_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_event_consumer_failures_event_id"), table_name="event_consumer_failures")
    op.drop_index(op.f("ix_event_consumer_failures_deleted_at"), table_name="event_consumer_failures")
    op.drop_index(op.f("ix_event_consumer_failures_consumer_key"), table_name="event_consumer_failures")
    op.drop_table("event_consumer_failures")
    op.drop_index(op.f("ix_documents_state"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
